apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: docker.io/bhuwanupadhyay/proximity/business
      context: ../business
      jib: {}
    - image: docker.io/bhuwanupadhyay/proximity/lbs
      context: ../lbs
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize:
    buildArgs:
      - --enable-helm
