openapi: 3.0.3
info:
  title: Proximity Service - Business
  description: |
    Business Service: to manage client business information.
  version: 1.0.0
servers:
  - url: 'https://api.proximity-service.local'
paths:
  /v1/businesses:
    post:
      description: |
        Add a business
      requestBody:
        required: true
        description: new business object
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                description: business object
                type: object
  /v1/businesses/:id:
    get:
      description: |
        Return detailed information about a business
      parameters:
        - name: id
          description: Business id
          required: true
          schema:
            type: integer
          in: path
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                description: business object
                type: object
    put:
      description: |
        Update details of a business
      parameters:
        - name: id
          description: Business id
          required: true
          schema:
            type: integer
          in: path
      requestBody:
        required: true
        description: updated on business object
        content:
          application/json:
            schema:
              type: object
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                description: business object
                type: object
    delete:
      description: |
        Delete a business
      parameters:
        - name: id
          description: Business id
          required: true
          schema:
            type: integer
          in: path
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                description: success response
                type: object
